### ISSUE TITLE
dragonplayer: Unknown option 'and-exit'

### ISSUE THREAD

**Issue by Crisp-Casper** [kamui-fin/discord-emote-menu#2]
dragonplayer 22.04.3
Arch

**Comment by kamui-fin** [comment]
The correct package for `dragon` on Arch Linux should be: https://aur.archlinux.org/packages/dragon-drop

For some reason, this package renames the binary to `dragon-drop`, so you will have to create a soft link in a user binary directory like `~/.local/bin`. For example:
```sh
ln -s /usr/bin/dragon-drop ~/.local/bin/dragon
```
Let me know if that fixes it. Thanks!

**Comment by Crisp-Casper** [comment]
> The correct package for `dragon` on Arch Linux should be: https://aur.archlinux.org/packages/dragon-drop
> 
> For some reason, this package renames the binary to `dragon-drop`, so you will have to create a soft link in a user binary directory like `~/.local/bin`. For example:
> 
> ```shell
> ln -s /usr/bin/dragon-drop ~/.local/bin/dragon
> ```
> 
> Let me know if that fixes it. Thanks!

installing dragon-drop fixed the issue, however the script only works properly from the terminal when i put it in my i3 config as shown
[code]

bindsym $mod+shift+m exec --no-startup-id /home/casper/discord-emote-menu/emote.sh -c -r /home/casper/discord-emote-menu/sample.rofi

[/code]

it pulls up the menu lets me select and everything just doesn't open dragon for the drop

**Comment by th3r00t** [comment]
did you make a symlink from dragon-drop to dragon? i will be testing on arch later, and will report findings.

**Comment by fizzleRaider** [comment]
I'm also on arch and ran into the same issue. It can be easily fixed by adding `-drop` after `dragon` in line 214.
`dragon $real_fn --and-exit` to `dragon-drop $real_fn --and-exit`.

**Comment by kamui-fin** [comment]
Just pushed a fix to automatically use `dragon-drop` on Arch. The symlink or line 214 modification is no longer needed.
