### ISSUE TITLE
xclip: -se: No such file or directory

### ISSUE THREAD

**Issue by Croldfish** [kamui-fin/discord-emote-menu#4]
got this error

**Comment by kamui-fin** [comment]
Which distribution are you on? Do you have the latest version of the repository? When did you sync the emotes?

**Comment by Tokariew** [comment]
the same on fedora…
changing in script `xclip -se c` to `xclip -selection clipboard` fix error for me
```
➜ xclip -version
xclip version 0.13
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
```
